### ISSUE TITLE
xray role changes owner of artifactory folder, causing error in artifactory

### ISSUE THREAD

**Issue by rockdreamer** [jfrog/JFrog-Cloud-Installers#147]
**Which installer**: Ansible

**Which product and version**: ansible 2.11.2 jfrog-platform collection 7.21.12

**Which operating system and version**: Ubuntu 20.04

**What happened**:

I used this playbook to install artifactory and xray on a single server

```
- hosts: postgres_servers
  roles:
    - jfrog.platform.postgres

- hosts: artifactory_servers
  roles:
    - jfrog.platform.artifactory

- hosts: xray_servers
  roles:
    - jfrog.platform.xray
```

While artifactory started working for a while, when the xray role ran, it chowned /opt/artifactory to user xray:xray!
I had to `chown -R artifactory:artifactory artifactory artifactory-pro-7.21.12 jfrog-artifactory-pro-7.21.12-linux.tar.gz `

**What you expected to happen**:

artifactory and xray to work without spending more than a day troubleshooting
