### ISSUE TITLE
[ansible/missioncontrol] Elasticsearch cluster status is yellow

### ISSUE THREAD

**Issue by Uquout7o** [jfrog/JFrog-Cloud-Installers#154]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug report

**Which installer**: Ansible

**Which product and version** (eg: ansible & collection version - 1.1.2): 7.24.3

**Which operating system and version**(eg: ubuntu & version - 20.4): Ubuntu 20.04.2

**What happened**: After installing mission control via the collection role, Elasticsearch cluster health API reports cluster status "yellow" and only one cluster node.

**What you expected to happen**: Elasticsearch cluster status being green, with 3 nodes.

**How to reproduce it** (as minimally and precisely as possible): Install mission control on a Ubuntu server and curl http://localhost:9200/_cluster/health

**Anything else we need to know**:
curl http://localhost:9200/_cluster/health output:
{"cluster_name":"elasticsearch","status":"yellow","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":10,"active_shards":10,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":9,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":52.63157894736842}

**Comment by chukka** [comment]
@Uquout7o is this a default platform collection installation with single node of mission control or HA setup ? Please share inventory file to debug further

**Comment by Uquout7o** [comment]
It's a 3 node HA installation of Mission Control.
Here's my inventory:
```
ArtifactoryVMs:
  children:
    artifactory:
      hosts:
        "artif01": {}
        "artif02": {}
        "artif03": {}
    artifactorydb:
      hosts:
        "artifdb01": {}
        "artifdb02": {}
    missioncontrol:
      hosts:
        "misco01":
          mc_ha_node_type: "master"
        "misco02":
          mc_ha_node_type: "slave"
        "misco03":
          mc_ha_node_type: "slave"
    xray:
      hosts:
        "xray01": {}
        "xray02": {}
        "xray03": {}
```
Logs are attached.

[elasticsearch_logs-20210823.tar.gz](https://github.com/jfrog/JFrog-Cloud-Installers/files/7030554/elasticsearch_logs-20210823.tar.gz)
