### ISSUE TITLE
[ansible/artifactory] hard-coded path

### ISSUE THREAD

**Issue by bbaassssiiee** [jfrog/JFrog-Cloud-Installers#267]
https://github.com/jfrog/JFrog-Cloud-Installers/blob/75b3c0cb03d6379d61ab45d4f3c25ce45519bcc4/Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/tasks/main.yml#L79

**Comment by bbaassssiiee** [comment]
This path depends on the distribution used. Blocks #195

Suggestion:

```yaml
dest: "{{ artifactory_nginx_cert_path }}"
```

**Comment by bbaassssiiee** [comment]
artifactory_nginx_key_path "/etc/pki/tls/private/cert.key"

**Comment by bbaassssiiee** [comment]
You could used these in the NGinx config templates too!
 ```text
 ssl_certificate      {{ ssl_certificate }};
 ssl_certificate_key  {{ ssl_certificate_key }};
```

**Comment by itssiri** [comment]
Thanks for reporting. Can you please raise a PR with the suggested fix? We will be happy to take it in next release.

**Comment by bbaassssiiee** [comment]
Naming will be:

```yaml
ssl_certificate_path: /etc/pki/tls/certs/
ssl_certificate_file: "{{ ssl_certificate_path }}/cert.pem"
ssl_certificate_key_path: /etc/pki/tls/private/
ssl_certificate_key_file: "{{ ssl_certificate_key_path }}/cert.key"
```
