### ISSUE TITLE
[ansible/artifactory] nginx_ssl needs SELinux boolean.

### ISSUE THREAD

**Issue by bbaassssiiee** [jfrog/JFrog-Cloud-Installers#268]
**Which installer**:
ansible

**Which product and version** (eg: ansible & collection version - 7.24.2):
artifactory-pro-7.55.3
jfrog.platform 

**Which operating system and version**(eg: ubuntu & version - 20.4):
AlmaLinux/RHEL8 (SELinux enforcing)

**Which product license** (Enterprise/Pro):
Not needed yet

**JFrog support reference** (if already raised with support team): 

**What happened**:
==> artifactory-error.log <==
2023/03/16 15:22:30 [crit] 18009#18009: *18 connect() to 127.0.0.1:8082 failed (13: Permission denied) while connecting to upstream, client: 192.168.xxx.yyy, server: test, request: "GET /ui/ HTTP/2.0", upstream: "http://127.0.0.1:8082/ui/", host: "alma1"

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
enable selinux configure NGinx with ssl as reverse proxy.

**Anything else we need to know**:

**This is the fix**

```yaml
- name: Set httpd_can_network_connect
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true
 ```
