### ISSUE TITLE
[ansible/artifactory] artifactory_start_service not working as expected in Ansible role

### ISSUE THREAD

**Issue by MadOtis** [jfrog/JFrog-Cloud-Installers#284]
**Is this a request for help?**:
A recent PR added the ability to specify the 'artifactory_start_service' flag to prevent Artifactory from re/starting when the Ansible playbook is used to create an AWS AMI image.  The flag isn't working as expected.  When specifying `artifactory_start_service: false` as a var in an Ansible playbook, the services is still trying to start/restart and is failing the playbook.  In our case, we're using the collection/roles to provision an AWS AMI image that does not have some items built in, such as master, join keys, license tokens, etc. (these get populated as part of a cloud-init function later when an instance is created from the base AMI), so the Artifactory service SHOULD NOT start during the AMI playbook run, but the current state of the playbook DOES try to start the service which, of course, fails due to not having essential values specified.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Which installer**:
Ansible Install/Update Role

**Which product and version** (eg: ansible & collection version - 7.24.2):
Ansible: (core 2.14.4)
Packer: 1.8.6
JFrog.platform: 10.12.1 

**Which operating system and version**(eg: ubuntu & version - 20.4):
MacOS: Ventura 13.3.1

**Which product license** (Enterprise/Pro):
Enterprise

**JFrog support reference** (if already raised with support team): 
None

**What happened**:
Tried to use the Collection's Artifactory role to create a no-license, no-join-key, no-master-key role to produce an AWS AMI image, but the packer/ansible provisioner fails due to the playbook not able to successfully start the Artifactory service after it is installed.  Leveraged the new 'artifactory_start_service' flag to tell the playbook NOT to try and start the service, but the playbook seemed to ignore the flag being set to 'FALSE' and tried to unsuccessfully start the service anyway.

**What you expected to happen**:
When specifying 'false' for the 'artifactory_start_service', it should honor the boolean value and NOT start the service.

**How to reproduce it** (as minimally and precisely as possible):
Create a simple playbook and add a task, such as:
```
  tasks:
    - name: Install Artifactory Service
      ansible.builtin.include_role:
        name: jfrog.platform.artifactory
      vars:
        artifactory_nginx_enabled: true
        artifactory_start_service: false
        artifactory_systemyaml_override: true
        artifactory_db_type: postgresql
        artifactory_db_driver: org.postgresql.Driver
```
and run the playbook.

**Anything else we need to know**:
Already created a fork to fix this, but created the issue for reference in the PR.
