### ISSUE TITLE
[ansible/artifactory] automate the configuration of a Artifactory installation

### ISSUE THREAD

**Issue by bbaassssiiee** [jfrog/JFrog-Cloud-Installers#290]
**Is this a request for help?**:
NO
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
# FEATURE REQUEST

Automate the configuration of Artifactory, namely:
- License Key(s)
- Base URL
- Proxy
- Repositories
- Users
- Permissions

**Which installer**:
Artifactory

**Which product and version** (eg: ansible & collection version - 7.24.2):
ansible & collection version

**Which operating system and version**(eg: ubuntu & version - 20.4):
RHEL 8.8

**Which product license** (Enterprise/Pro):
Enterprise

**JFrog support reference** (if already raised with support team): 
260703

**What happened**:
I encountered a wizard! Had to click and type!

**What you expected to happen**:
I'd rather use parameters and Ansible's **template** module.

**How to reproduce it** (as minimally and precisely as possible):
Install Artifactory.

**Anything else we need to know**:

Another step can be automated like this:

```yaml
- name: Artifactory Bootstrap YAML File
  ansible.builtin.template:
    src: artifactory.config.import.yml.j2
    dest: /opt/jfrog/artifactory/var/etc/artifactory/artifactory.config.import.yml
    mode: 0644
  notify: Restart Artifactory
 ```
