### ISSUE TITLE
[ansible/xray] db-util / db5.3-util package installation on Ubuntu 20

### ISSUE THREAD

**Issue by olwe0002** [jfrog/JFrog-Cloud-Installers#296]
Is this a BUG REPORT or FEATURE REQUEST? (choose one): bug
Which installer: ansible
Which product and version : ansible & JFrog Platform 10.12.3 release
Which operating system and version(eg: ubuntu & version - 20.4): ubuntu & version - 20.4
Which product license (Enterprise/Pro): Enterprise

**What happened**:

There are multiple problems with the current code regarding the installation of the db packages on Ubuntu 20:
1. the provided default mask for db5...

```yaml
xray_db_util_search_filter:
  ubuntu20:
    db5: 'db5.3-util.*dfsg.*ubuntu.*amd64\.deb'
  
```
...matches both existing files:

```yaml
db5.3-util_5.3.28+dfsg1-0.6ubuntu2_amd64.deb
db5.3-util_5.3.28+dfsg1-0.8ubuntu3_amd64.deb
```
if `db5.3-util_5.3.28+dfsg1-0.8ubuntu3_amd64.deb` is matched first, it fails on Ubuntu 20 because of a dependency problem. if the other one matches first, it works. Which one is matched first, seems to be random. So my workaround was to define in the group vars:

```yaml
xray_db_util_search_filter:
  ubuntu20:
    db5: 'db5.3-util_5.3.28+dfsg1-0.6ubuntu2_amd64.deb'
```

This ensures the right file to be matched.

2. the installation of the second package, `db-util` works fine without any changes. But the problem is if there is any update on OS level, which updates the package to a newer version, the task fails on future runs, as there is already a newer version installed:

```
TASK [jfrog.platform.xray : Install db-util package] ***************************
fatal: [server-name-here]: FAILED! => {
    "changed": false
}
MSG:
A later version is already installed
```

To go on here, I have to set a invalid file mask to skip the installation, as this skips the task completely. I assume the same might happen in the future for the db5 package.

**What you expected to happen**:

The package installation is done in a stable way which always works, even if the installed package is updated via package manager in the meantime. As on Ubuntu 20 the needed packages are availble via `apt` named `db-util` and `db5.3-util`, without adding additional repo sources (!), this should be the way to go instead of installing outdated versions via `.deb` files.

**Comment by chukka** [comment]
@olwe0002  can you verify the fix posted [here](https://github.com/jfrog/JFrog-Cloud-Installers/pull/297/files)

**Comment by olwe0002** [comment]
as your solution does not fix problem number 2 (newer version gets installed beside the xray installer), we did go another way:

1. disable the installation by setting an invalid file mask:
```
xray_db_util_search_filter:
  ubuntu20:
    db5: invalid
    db: invalid
```
adding a preparation task to ensure that the latest avaliable package  is installed via apt:

```
- name: Install db-util packages
  ansible.builtin.apt:
    name:
      - db-util
      - db5.3-util
    update_cache: yes
    cache_valid_time: 3600
    state: present
```

of course this works only on debian based systems in this way (apt module), but ensures not to fail on package updates via apt update. maybe it helps someone in the same situation
