### ISSUE TITLE
[artifactory/ansible] Check certificate and certificate_key not needed when: not ssl_certificate_install 

### ISSUE THREAD

**Issue by bbaassssiiee** [jfrog/JFrog-Cloud-Installers#301]
https://github.com/jfrog/JFrog-Cloud-Installers/blob/eb802aacb2c5b6caf3bb35d7ff37febee142e986/Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/tasks/main.yml#L5

**Comment by bbaassssiiee** [comment]
Workaround: define these vars

**Comment by bbaassssiiee** [comment]
I have these because changing certs is independent of deploying Artifactory.

```yaml
# Two dummy vars
certificate: self_managed
certificate_key: self_managed
```
