### ISSUE TITLE
[ansible/artifactory] No input validation on database credentials

### ISSUE THREAD

**Issue by bbaassssiiee** [jfrog/JFrog-Cloud-Installers#311]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

The looping in the creation tasks for user, database and privileges in the postgres role does not fail on undefined values. Input validation seems to be missing, and the logging of `item=None` is not so useful.

```
TASK [jfrog.platform.postgres : Hold until Postgresql is up and running] *******
task path: /home/vsts/.ansible/collections/ansible_collections/jfrog/platform/roles/postgres/tasks/install.yml:78
ok: [localhost] => {"changed": false, "elapsed": 0, "match_groupdict": {}, "match_groups": [], "path": null, "port": 5432, "search_regex": null, "state": "started"}

TASK [jfrog.platform.postgres : Create user] ***********************************
task path: /home/vsts/.ansible/collections/ansible_collections/jfrog/platform/roles/postgres/tasks/install.yml:84
changed: [localhost] => (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": true}
changed: [localhost] => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": true}

TASK [jfrog.platform.postgres : Create database] *******************************
task path: /home/vsts/.ansible/collections/ansible_collections/jfrog/platform/roles/postgres/tasks/install.yml:97
changed: [localhost] => (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": true}
changed: [localhost] => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": true}

TASK [jfrog.platform.postgres : Grant privs on db] *****************************
task path: /home/vsts/.ansible/collections/ansible_collections/jfrog/platform/roles/postgres/tasks/install.yml:113
ok: [localhost] => (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
ok: [localhost] => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
```

**Which installer**:
Ansible

**Which product and version** (eg: ansible & collection version - 7.24.2):
ansible-core jfrog.platform (latest)

**Which operating system and version**(eg: ubuntu & version - 20.4):
RHEL8

**Which product license** (Enterprise/Pro):
Edge

**JFrog support reference** (if already raised with support team): 

**What happened**:

No database was created. `systemctl status artifactory` says it's started, but it's not healthy. 

**What you expected to happen**:
Assertion on missing parameters.

**How to reproduce it** (as minimally and precisely as possible):
Use a dynamic inventory.

**Anything else we need to know**:

**Comment by bbaassssiiee** [comment]
# how to test

```yaml
#!/usr/bin/env ansible-playbook
---

- name: Check inputs
  hosts: all

  tasks:

    - name: Assert database credentials are defined
      ansible.builtin.assert:
        that:
          - curr_user.username is defined
          - curr_user.password is defined
      loop: "{{ database | dict2items | map(attribute='value') | list }}"
      loop_control:
        loop_var: curr_user
      when: curr_user.enabled | bool
```
