### ISSUE TITLE
[ansible/artifactory] install.yml task template bootstrap.creds.j2 - it looks for bootstrap.creds instead of bootstrap.creds.j2

### ISSUE THREAD

**Issue by tom9eiger** [jfrog/JFrog-Cloud-Installers#342]
**Which installer**:
*ansible & collection version - 10.16.0

**Which operating system and version**
Controller Node:
Arch Linux with kernel 6.1.60-1-lts

Manged Node:
Red Hat Enterprise Linux release 9.2 (Plow)

**Which product license** (Enterprise/Pro):
Pro

**JFrog support reference** (if already raised with support team): 
No

**What happened**:
ASK [jfrog.platform.artifactory : Set up Artifactory admin account] ***************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hostname]: FAILED! => {"changed": false, "msg": "Could not find or access 'bootstrap.creds

**What you expected to happen**:
Use template bootstrap.creds.j2

**How to reproduce it** (as minimally and precisely as possible):
Running without own template 

**Anything else we need to know**:
Change in the artifactory role in task file install.yml following:
```yaml
- name: Set up Artifactory admin account 
  ansible.builtin.template:
    src: bootstrap.creds
    dest: "{{ artifactory_home }}/var/etc/access/"
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    mode: 0600
  when: 
    - artifactory_admin_username is defined
    - artifactory_admin_password is defined
  notify: Restart artifactory
```
to:
```yaml
- name: Set up Artifactory admin account 
  ansible.builtin.template:
    src: bootstrap.creds.j2
    dest: "{{ artifactory_home }}/var/etc/access/"
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    mode: 0600
  when: 
    - artifactory_admin_username is defined
    - artifactory_admin_password is defined
  notify: Restart artifactory
```
