### ISSUE TITLE
[ansible/artifactory] Allow to configure custom trusted certificates

### ISSUE THREAD

**Issue by jcoste-orange** [jfrog/JFrog-Cloud-Installers#368]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Which installer**:
Ansible

**Which product and version** (eg: ansible & collection version - 7.24.2):
Artifactory 7.71.10

**Which operating system and version**(eg: ubuntu & version - 20.4):
Ubuntu 20.0

**Which product license** (Enterprise/Pro):
Enterprise

**JFrog support reference** (if already raised with support team): 

**What happened**:
I need to configure a trusted certificate to access an internal S3 server for my binary store.
I can't configure it before playing the artifactory role (as folders are not yet created).
If I run the role, Artifactory tries to start and fails as it can't access to the S3 server.

**What you expected to happen**:
It would be nice to be able to configure custom trustes certificates in the artifactory role.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by chukka** [comment]
@jcoste-orange Thanks for reaching out ! can you share more information with an example

**Comment by jcoste-orange** [comment]
Our S3 server is using a self signed certificate.
So we have to store the certificate in /opt/jfrog/artifactory/var/etc/security/keys/trusted/.

Today we have to patch the role to add a task like this :

```yaml
    - name: copy custom cert
      become: true
      ansible.builtin.copy:
        src: "<local_custom_cert.crt>"
        dest: "/opt/jfrog/artifactory/var/etc/security/keys/trusted/custom.crt"
        owner: "{{ artifactory_user }}"
        group: "{{ artifactory_group }}"
        mode: 0600
        remote_src: true
```
