### ISSUE TITLE
[ansible/postgresql] Use the official redhat.rhel_system_roles.postgresql collection to setup postgres

### ISSUE THREAD

**Issue by ghost** [jfrog/JFrog-Cloud-Installers#381]
For RHEL operating systems, you may use the official red hat collection to setup Postgres:

redhat.rhel_system_roles.postgresql
[https://console.redhat.com/preview/ansible/automation-hub/repo/published/redhat/rhel_system_roles/docs/README_postgresql/](https://console.redhat.com/preview/ansible/automation-hub/repo/published/redhat/rhel_system_roles/docs/README_postgresql/)

[https://galaxy.ansible.com/ui/repo/published/fedora/linux_system_roles/docs/README_postgresql/](https://galaxy.ansible.com/ui/repo/published/fedora/linux_system_roles/docs/README_postgresql/)

```
- name: Include RHEL Postgres setup role
  ansible.builtin.include_role:
    name: redhat.rhel_system_roles.postgresql
  vars:
    postgresql_version: "{{ jfrog_postgresql__version }}"
    postgresql_password: "{{ jfrog_postgresql__password }}"
    postgresql_ssl_enable: "{{ jfrog_postgresql__ssl_enable }}"
    postgresql_cert_name: "{{ jfrog_postgresql__cert_path }}"
    postgresql_certificates:
      - name: "{{ jfrog_postgresql__gen_cert_name }}"
        dns: "{{ jfrog_postgresql__gen_cert_dns }}"
        ca: "{{ jfrog_postgresql__gen_cert_ca }}"
```
