### ISSUE TITLE
[ansible/artifactory] artifactory_flavour variable does nothing

### ISSUE THREAD

**Issue by jcox10** [jfrog/JFrog-Cloud-Installers#409]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Which installer**: N/A

**Which product and version** (eg: ansible & collection version - 7.24.2): 10.19.4

**Which operating system and version**(eg: ubuntu & version - 20.4): RHEL9

**Which product license** (Enterprise/Pro): Doesn't matter

**JFrog support reference** (if already raised with support team): N/A

**What happened**:

The ansible variable `artifactory_flavour` doesn't do anything, it is listed in the default vars:
```
# Pick the Artifactory flavour to install, can be also cpp-ce/jcr/pro
artifactory_flavour: pro
```

**What you expected to happen**: Changing the variable should change the installer

**How to reproduce it** (as minimally and precisely as possible): Search all of the files for the variable, it is not used.

**Anything else we need to know**:

**Comment by vijayreddy1991** [comment]
@jcox10 Thanks for reporting we will fix this in next release

**Comment by jcox10** [comment]
Looks like the var has been removed in `11.0.4`, thanks for that.  In case anyone is wondering, you can use this ansible collection to install the opensource JCR by setting the following variables:
```yaml
artifactory_tar_file_name: "jfrog-artifactory-jcr-{{ artifactory_version }}-linux.tar.gz"
artifactory_tar: "https://releases.jfrog.io/artifactory/bintray-artifactory/org/artifactory/jcr/jfrog-artifactory-jcr/{{ artifactory_version }}/{{ artifactory_tar_file_name }}"
artifactory_untar_home: "{{ jfrog_home_directory }}/artifactory-jcr-{{ artifactory_version }}"
```
