### ISSUE TITLE
[ansible/postgresql] method key for postgres_allowed_hosts doesn't work

### ISSUE THREAD

**Issue by AlexeyMinasyan** [jfrog/JFrog-Cloud-Installers#411]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Which installer**: N/A

**Which product and version** (eg: ansible & collection version - 7.24.2): Ansible - 2.14.3,  jfrog.platform       10.19.4

**Which operating system and version**(eg: ubuntu & version - 20.4): Debian 12

**Which product license** (Enterprise/Pro): Pro

**JFrog support reference** (if already raised with support team): 

**What happened**: 
Variable postgres_allowed_hosts.method doesn't work. 
By looking at [code](https://github.com/jfrog/JFrog-Cloud-Installers/blob/master/Ansible/ansible_collections/jfrog/platform/roles/postgres/templates/pg_hba.conf.j2#L16) it seems that there is a typo in template. 
Method is not using host iterator, but item and also looking for auth key instead of method 

**What you expected to happen**:
Method should be appropriately populated during pg_hba.conf template generation

**How to reproduce it** (as minimally and precisely as possible):
Execute postgresql role with variable like this
```yaml
postgres_allowed_hosts:
  - {
      type: "host",
      database: "all",
      user: "all",
      address: "0.0.0.0/0",
      method: "md5",
    }
```

Method will be trust instead of expected md5

**Anything else we need to know**:
