### ISSUE TITLE
[ansible/xray] "Import CentOS GPG public key" hardcoded URL

### ISSUE THREAD

**Issue by gianluca-fiasco** [jfrog/JFrog-Cloud-Installers#413]
_Is this a BUG REPORT or FEATURE REQUEST? (choose one):_ Bug

_Which installer:_
Ansible

_Which product and version (eg: ansible & collection version - 7.24.2)_:
Ansible collection multiple versions

_Which operating system and version(eg: ubuntu & version - 20.4):_
RHEL8

_Which product license (Enterprise/Pro):_
Enterprise+

_What happened:_

This task should be customizable, and the URL should not be hardcoded.

The task located at [this link](https://github.com/jfrog/JFrog-Cloud-Installers/blob/master/Ansible/ansible_collections/jfrog/platform/roles/xray/tasks/rabbitmq/setup/RedHat.yml#L26C1-L30C19):

```yaml
- name: Import CentOS GPG public key
  become: true
  ansible.builtin.rpm_key:
    key: https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Official
    state: present
```

has the following issues:

- **It is not idempotent:** This task will run every time, regardless of the key’s presence.
- **External URL:** The URL points to an external resource, which may violate security policies.
- 
In my company (an S&P 500 firm with 30,000 employees), we are not permitted to retrieve files from the internet. Ideally, this key should be fetched from an internal server or hosted on Artifactory itself.
