### ISSUE TITLE
[ansible/platform] environment variables missing for most fetching tasks

### ISSUE THREAD

**Issue by EmptyByte** [jfrog/JFrog-Cloud-Installers#415]
Many companies have proxies.. For the collection to work and not fail at the third step we need to be able to pass proxy environment variables to the role.

Please add a variable to specify environment variables on tasks such as below with http_proxy and https_proxy vars.

```
    - name: Import PostgreSQL GPG public key
      become: true
      ansible.builtin.rpm_key:
        key: "https://download.postgresql.org/pub/repos/yum/keys/PGDG-RPM-GPG-KEY-RHEL"
        state: present
      register: download_postgresql_key
      until: download_postgresql_key is success
      retries: 3
      delay: 3
```

To

```
    - name: Import PostgreSQL GPG public key
      become: true
      ansible.builtin.rpm_key:
        key: "https://download.postgresql.org/pub/repos/yum/keys/PGDG-RPM-GPG-KEY-RHEL"
        state: present
      environment: "{{ CUSTOMER_ENVIRONMENT_VARS }}"
      register: download_postgresql_key
      until: download_postgresql_key is success
      retries: 3
      delay: 3
```

**Comment by EmptyByte** [comment]
Specifying it at play level worked. Closing.
```
environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
```
