### ISSUE TITLE
[ansible/artifactory] Destination /etc/cron.allow does not exist

### ISSUE THREAD

**Issue by EmptyByte** [jfrog/JFrog-Cloud-Installers#420]
In most roles if the following variable is set to true:
```
# Allow artifactory user to create crontab rules
artifactory_allow_crontab: false
```

Then you may face:
```
FAILED! => {"changed": false, "msg": "Destination /etc/cron.allow does not exist !", "rc": 257}
```

Because the following task:
```
- name: Allow using crontab
  ansible.builtin.lineinfile:
    path: /etc/cron.allow
    line: "{{ artifactory_user }}"
    state: present
  when: artifactory_allow_crontab
```

Is missing:
```
create: true
```
