### ISSUE TITLE
[ansible/xray] Expect - extra characters after close-quote

### ISSUE THREAD

**Issue by EmptyByte** [jfrog/JFrog-Cloud-Installers#424]
The following error is returned when running tasks `Interactive with expect`:

```
extra characters after close-quote
    while executing
"send ""h"
    invoked from within
"expect {
                    -nocase -re {(data|installation) directory \(.*} {
                send "/opt/jfrog/xray\n"
            }
               ..."
    ("while" body line 2)
    invoked from within
"while { $CYCLE_END == 0 } {
    expect {
                    -nocase -re {(data|installation) directory \(.*} {
                send "/opt/jfrog/xray\..."
```

`Ansible/ansible_collections/jfrog/platform/roles/xray/tasks/expect.yml`

```
- name: Prepare expect scenario script
  ansible.builtin.set_fact:
    expect_scenario: |
        set timeout 300
        spawn {{ exp_executable_cmd }}
        expect_before timeout { exit 1 }
        set CYCLE_END 0
        set count 0

        while { $CYCLE_END == 0 } {
            expect {
                {% for each_request in exp_scenarios %}
                    -nocase -re {{ '{' }}{{ each_request.expecting }}.*} {
                        send "{{ each_request.sending }}\n"
                    }
                {% endfor %}
                eof {
                    set CYCLE_END 1
                }
            }
            set count "[expr $count + 1]"
            if { $count > 16} {
                exit 128
            }
        }

        expect eof
        lassign [wait] pid spawnid os_error_flag value

        if {$os_error_flag == 0} {
            puts "INSTALLER_EXIT_STATUS-$value"
        } else {
            puts "INSTALLER_EXIT_STATUS-$value"
        }
```

Maybe the task should have proper closing:

```
- name: Prepare expect scenario script
  ansible.builtin.set_fact:
    expect_scenario: |
        set timeout 300
        spawn {{ exp_executable_cmd }}
        expect_before timeout { exit 1 }
        set CYCLE_END 0
        set count 0

        while { $CYCLE_END == 0 } {
            expect {
                {% for each_request in exp_scenarios %}
                    -nocase -re {{ '{' }}{{ each_request.expecting }}.*{{ '}' }} {
                        send "{{ each_request.sending }}\n"
                    }
                {% endfor %}
                eof {
                    set CYCLE_END 1
                }
            }
            set count "[expr $count + 1]"
            if { $count > 16 } {
                exit 12
            }
        }

        expect eof
        lassign [wait] pid spawnid os_error_flag value

        if {$os_error_flag == 0} {
            puts "INSTALLER_EXIT_STATUS-$value"
        } else {
            puts "INSTALLER_EXIT_STATUS-$value"
        }
```

**Comment by chukka** [comment]
@EmptyByte  Thanks for raising this issue , Would you mind  raising this as a Pull Request, Happy to take this in upcoming releases :)

**Comment by EmptyByte** [comment]
@chukka sorry, I could not test my assumption. This expect scenario is hard to manage (also it may not return the exit code and thus may not fail correctly.

You can try to force quote:
```
send "{{ each_request.sending }}\n"
```
to
```
send "{{ each_request.sending | quote }}\n"
```

Alternatively we may revisit the structure completely so it easier (giving the following more or less) ? 

```
# Variable for expect script
xray_expect_install: "./install.sh -u {{ xray_user }} -g {{ xray_group }}"

# Scenario for expect script
xray_expect_scenario:
  default:
    - expecting: "(data|installation) directory \\("
      sending: "{{ xray_home }}"
    - expecting: "jfrog url( \\(.+\\))?:(?!.*Skipping prompt)"
      sending: "{{ jfrog_url }}"
    - expecting: "join key:(?!.*Skipping prompt)"
      sending: "{{ join_key }}"
    - expecting: "please specify the ip address of this machine(?!.*Skipping prompt)"
      sending: "{{ ansible_host }}"
    - expecting: "are you adding an additional node"
      sending: "{% if xray_ha_node_type is defined and xray_ha_node_type == 'master' %}n{% else %}y{% endif %}"
    - expecting: "do you want to install postgresql"
      sending: "n"
    - expecting: "(postgresql|database) url"
      sending: "{{ xray_db_url }}"
    - expecting: "(postgresql|database) password"
      sending: "{{ xray_db_password }}"
    - expecting :"(postgresql|database) username"
      sending: "{{ xray_db_user }}"
    - expecting: "confirm database password"
      sending: "{{ xray_db_password }}"
    - expecting: "rabbitmq active node name:"
      sending: "{{ ansible_machine_id }}"
    - expecting: "rabbitmq active node ip:"
      sending: "{{ ansible_host }}"

# Expect script
distribution_expect_script: |
  set timeout 300
  spawn {{ xray_expect_install }}
  expect_before timeout { exit 1 }
  set CYCLE_END 0
  set count 0

  while { $CYCLE_END == 0 } {
      expect {
          {% for request in xray_expect_scenario.default %}
              -nocase -re {{ '{' }}{{ request.expecting }}.*{{ '}' }} {
                  send "{{ request.sending | quote }}\r"
              }
          {% endfor %}
          eof {
              set CYCLE_END 1
          }
      }
      set count "[expr $count + 1]"
      if { $count > 16} {
          exit 128
      }
  }

  expect eof
  lassign [wait] pid spawnid os_error_flag value

  if {$os_error_flag == 0} {
    puts "exit status: $value"
  } else {
    puts "errno: $value"
  }
```

Then inside `install.yml`

```
- name: Check if install.sh wrapper script exists
  become: true
  ansible.builtin.stat:
    path: "{{ xray_install_script_path }}/install.sh"
  register: stat_xray_install_script

- name: Include expect variables
  ansible.builtin.include_vars: script/expect.yml
  when:
    - stat_xray_install_script.stat.exists
    - not xray_upgrade_only | bool or 
      (download_xray is defined and download_xray is succeeded and xray_upgrade_only | bool)

- name: Execute expect script
  become: true
  ansible.builtin.shell:
    cmd: "{{ xray_expect_script }}"
    executable: '/usr/bin/expect'
    chdir: "{{ xray_install_script_path }}"
  environment:
    YQ_PATH: "{{ xray_thirdparty_path }}/yq"
  register: reg_expect_script_results
  when:
    - stat_xray_install_script.stat.exists
    - not xray_upgrade_only | bool or 
      (download_xray is defined and download_xray is succeeded and xray_upgrade_only | bool)
```
