### ISSUE TITLE
[ansible/platform] Firewalld is not configured - communication failures.

### ISSUE THREAD

**Issue by EmptyByte** [jfrog/JFrog-Cloud-Installers#425]
Firewalld needs to be configured to allow communication between hosts otherwise tasks such as below will fail.
Alternatively, inform that firewalld is not supported in your documentation and that the user has to take care of it.

```
- name: Make sure xray is up and running
  ansible.builtin.uri:
    url: http://127.0.0.1:8082/router/api/v1/system/health
    timeout: 130
    status_code: 200
  register: result
  until: result is succeeded
  retries: 25
  delay: 5
  when:
    - not ansible_check_mode
    - xray_start_service | bool
```
