### ISSUE TITLE
[ansible/postgres] RHEL 7.8 - ''postgres_server_initdb_become'' is undefined'

### ISSUE THREAD

**Issue by wdrury-uk** [jfrog/JFrog-Cloud-Installers#58]
Hi

Using collection - jfrog.installers:1.1.2'

Trying to use collection on a local virtualbox lab and on our RHEL 7.8 VM install runs to the initialize PostgresSQL database cluster" task then errors as below.  

```
TASK [jfrog.installers.postgres : initialize PostgreSQL database cluster] ****************************************************
task path: /root/.ansible/collections/ansible_collections/jfrog/installers/roles/postgres/tasks/main.yml:33
fatal: [postgres]: FAILED! =>
  msg: 'The field ''become'' has an invalid value, which includes an undefined variable. The error was: ''postgres_server_initdb_become'' is undefined'
```

On executing with -vv verbose I can see the variables being created by the collections _**postgres**_ role as follows:
```
TASK [jfrog.installers.postgres : define distribution-specific variables] ****************************************************
task path: /root/.ansible/collections/ansible_collections/jfrog/installers/roles/postgres/tasks/main.yml:2
ok: [postgres] => changed=false
  ansible_facts:
    postgres_server_cmd_initdb: /usr/pgsql-{{ postgres_server_version }}/bin/postgresql{{ postgres_server_pkg_version }}-setup initdb -D
    postgres_server_config_data_directory: null
    postgres_server_config_external_pid_file: null
    postgres_server_config_hba_file: null
    postgres_server_config_ident_file: null
    postgres_server_config_location: '{{ postgres_server_data_location }}'
    postgres_server_data_location: /var/lib/pgsql/{{ postgres_server_version }}/data
    postgres_server_service_name: postgresql-{{ postgres_server_version }}
  ansible_included_var_files:
  - /root/.ansible/collections/ansible_collections/jfrog/installers/roles/postgres/vars/RedHat.yml
```

As you can see it appears the required _**postgres_server_initdb_become var**_ is missing from the _<role>/postgres/vars/RedHat.yml_ although I have checked and it is included in the _RedHat_pg-9.6.yml_ vars file.  Should this one have been used and pulled through the play instead or aswell?
