### ISSUE TITLE
[ansible/artifactory] providing Artifactory license has no effect

### ISSUE THREAD

**Issue by weakcamel** [jfrog/JFrog-Cloud-Installers#82]
**Is this a request for help?**:

No.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug report.

**Which installer**:

Ansible installer.

**Which product and version** (eg: ansible & collection version - 1.1.2):

Artifactory 7.10.2

Ansible collection 1.1.2 from Galaxy.

**Which operating system and version**(eg: ubuntu & version - 20.4):

Ubuntu 18.04.5 LTS

**What happened**:

Initially I ran installation of Artifactory with basic settings (see details in https://github.com/jfrog/JFrog-Cloud-Installers/issues/76) and it came up with Getting Started dialog, asking me to change password  and apply the license.

I need the installation to be fully automated so I specified the license for this instance:

```
artifactory_is_primary: true
artifactory_license1: "this is the license"
```

but it had no effect. I can see that the value is used:

```
TASK [jfrog.installers.artifactory : use license file] ******************************************************************************************************************************************************
task path: /Users/myuser/git/auto/galaxy-roles/ansible_collections/jfrog/installers/roles/artifactory/tasks/install.yml:167
skipping: [artifactory.lab.mydomain.com] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [jfrog.installers.artifactory : use license strings] ***************************************************************************************************************************************************
task path: /Users/myuser/git/auto/galaxy-roles/ansible_collections/jfrog/installers/roles/artifactory/tasks/install.yml:174
redirecting (type: lookup) ansible.builtin.hashi_vault to community.general.hashi_vault
changed: [artifactory.lab.mydomain.com] => {"changed": true, "checksum": "82f4c40b55b899e7b9ba9667722b59344b880427", "dest": "/opt/jfrog/artifactory/var/etc/artifactory/artifactory.cluster.license", "gid": 0, "group": "root", "md5sum": "b6777008a3f2d35a27b7b67b917afed5", "mode": "0644", "owner": "root", "size": 933, "src": "/tmp/.ansible-adminuser/ansible-tmp-1613384191.057653-5889-7286596822962/source", "state": "file", "uid": 0}
```

but the UI still prompts me to enter the license afterwards.

**What you expected to happen**:

After specifying the license in Ansible variables, I expect the license to be applied.

**How to reproduce it** (as minimally and precisely as possible):

```
- name: Install and configure Artifactory
  hosts: artifactory_test
  become: true
  tasks:
    - include_role:
        name: jfrog.installers.postgres
    - include_role:
        name: jfrog.installers.artifactory

```

variables:

```
artifactory_is_primary: true
artifactory_license1: "this is the license"

# postgres role:
db_users:
  - db_user: "artifactory"
    db_password: "mypassword"

# artifactory role:
server_name: "{{ ansible_fqdn }}"
artifactory_version: 7.10.2

artifactory_is_primary: true
db_download_url: "https://jdbc.postgresql.org/download/postgresql-42.2.18.jar"
db_type: "postgresql"
db_driver: "org.postgresql.Driver"
db_url: "jdbc:postgresql://localhost:5432/artifactory"
db_user: "artifactory"
db_password: "mypassword"

```

**Anything else we need to know**:

1. Arguably this may be not a bug but a new feature request. Documentation for the Artifactory role isn't very clear:
    https://github.com/jfrog/JFrog-Cloud-Installers/tree/master/Ansible/ansible_collections/jfrog/installers/roles/artifactory#primary-vars-vars-used-by-the-primary-artifactory-server
    From end user's perspective  - If installer is asking me to provide the license and I do, it's a reasonable expectation for it to apply it; otherwise - what is the point of that?
1. https://www.jfrog.com/confluence/display/JFROG/Artifactory+Bootstrap+YAML+File suggests creating a bootstrap config which is what I'll be trying to do on my own; presumabely the Ansible installer collection should also generate such bootstrap Yaml out of the specified `artifactory_license1-5` variables (or the input file)
